# -*- coding: utf-8 -*-
"""INDICE C y E.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mo2J1tBRaVqFpZi4AaoUFsf3Sp2YjMx3
"""

from google.colab import drive
drive.mount('/content/drive/')

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# INDICES SST (C y E)
indice = pd.read_csv("/content/drive/MyDrive/TPM_II/datos/indice_c_y_e/ecindex_ersstv5_CSV.csv")
indice