# -*- coding: utf-8 -*-
"""PISCO (PP).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oAg4LY38OhyjzrPmRrKO8hB3K27CCQl
"""

from google.colab import drive
drive.mount('/content/drive/')

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# PISCOt v1.2 (Prec: PRECIPITACION)
PP = xr.open_dataset("/content/drive/MyDrive/TPM_II/datos/PISCO_precipitation/PISCOp.nc")
PP