# -*- coding: utf-8 -*-
"""shp PERÚ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ImUZImkh5H_xLlOKM_TeSiR6fQnX7b6r
"""

from google.colab import drive
drive.mount('/content/drive/')

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install geopandas
# !pip install rioxarray

import rioxarray
from geopandas import read_file as gpd_read_file

shp_Peru = gpd_read_file('/content/drive/MyDrive/TPM_II/datos/Google_Colab_temp/shps/Departamentos.shp')
shp_Peru.plot()