# -*- coding: utf-8 -*-
"""Data Índice C (NOV).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbcalGdoO1r7oG8m6j0qHc9NfChPr-lE
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_indices_3 = pd.read_csv("/content/drive/MyDrive/PROYECTO FINAL/INDICE C y E (1950-2006)_2/df_indice_CyE(1950-2006)_2.csv")
df_indices_3

df_indice_C = df_indices_3.drop(columns=["E_index"])
df_indice_C

df_indice_C["Fecha"] = pd.to_datetime(df_indice_C["Fecha"], utc=True)

df_indice_C.set_index("Fecha", inplace=True)

df_indice_C

df_indice_C1 = df_indice_C[df_indice_C.index.month==11]
df_indice_C1

df_indice_C1_1= df_indice_C1.copy()

df_indice_C1_1.index.year

df_indice_C1_1["FECHA"] = df_indice_C1_1.index.year
df_indice_C1_1.head()

df_C_1= df_indice_C1_1.set_index("FECHA")
df_C_1

"""# GUARDAR ARCHIVO CSV"""

df_C_1.to_csv("indice_C_(NOV).csv")

from google.colab import files
files.download("indice_C_(NOV).csv")