# -*- coding: utf-8 -*-
"""data shp Loreto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g5TOalkWRvotFoUeIxAy4MXXD2iKOvRF
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install geopandas
# !pip install rioxarray

import rioxarray
from geopandas import read_file as gpd_read_file

"""# ANOMALIA DE PRECIPITACION"""

Pisco_anom_mensual = xr.open_dataset("/content/drive/MyDrive/PROYECTO FINAL/PP anom mensual/Pisco_anom_mensual.nc")
Pisco_anom_mensual

"""# shp PERÚ"""

shp_Peru = gpd_read_file('/content/drive/MyDrive/TPM_II/datos/Google_Colab_temp/shps/Departamentos.shp')
shp_Peru.plot()

def xr_crop(shp_i, netcdf_i):
  
  # get box
  box_i = shp_i.total_bounds
  
  # crop based on box
  crop_netcdf_i = netcdf_i.where((netcdf_i["longitude"] > box_i[0]) & # min lon
                                 (netcdf_i["longitude"] < box_i[2]) & # max lon
                                 (netcdf_i["latitude"] > box_i[1]) & # min lat
                                 (netcdf_i["latitude"] < box_i[3]), # max lat
                                 drop = True)
  
  return crop_netcdf_i

def xr_shp_to_grid(shp_i, netcdf_array):

  # get real box
  shp_i_geometry = shp_i.geometry

  # adding crs
  mask = netcdf_array.rio.set_crs(shp_i.crs)

  # "rasterizing"
  mask = mask.rio.clip(shp_i_geometry, drop = False)

  # making "True/False" values
  mask.values[~np.isnan(mask.values)] = 1

  return mask.drop(["time", "spatial_ref"])


def xr_mask(grid_mask, netcdf_i):

  # masking
  mask_netcdf_i = netcdf_i.where(grid_mask == True)

  return mask_netcdf_i

shp_Peru

"""# LORETO"""

shp_exp = shp_Peru.iloc[[15]]
shp_exp.plot()

Pisco_anom_mensual_Loreto = xr_crop(shp_i=shp_exp, netcdf_i=Pisco_anom_mensual)
Pisco_anom_mensual_Loreto

shp_exp_grid = xr_shp_to_grid(shp_i = shp_exp, 
                              netcdf_array = Pisco_anom_mensual_Loreto.Prec.isel(time=15))


Pisco_anom_masked_Loreto = xr_mask(grid_mask = shp_exp_grid,
                             netcdf_i = Pisco_anom_mensual_Loreto)

Pisco_anom_masked_Loreto

"""# GUARDAR ARCHIVO """

Pisco_anom_masked_Loreto = Pisco_anom_masked_Loreto.to_netcdf("Pisco_anom_masked_Loreto.nc")

from google.colab import files
files.download("Pisco_anom_masked_Loreto.nc")