# -*- coding: utf-8 -*-
"""Data Índice E (DIC).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TRz_um4fljRrUf-_8B0vFnnzZ7Wmy9io
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_indices_3 = pd.read_csv("/content/drive/MyDrive/PROYECTO FINAL/INDICE C y E (1950-2006)_2/df_indice_CyE(1950-2006)_2.csv")
df_indices_3

df_indice_E = df_indices_3.drop(columns=["C_index"])
df_indice_E

df_indice_E["Fecha"] = pd.to_datetime(df_indice_E["Fecha"], utc=True)

df_indice_E.set_index("Fecha", inplace=True)

df_indice_E

df_indice_E1 = df_indice_E[df_indice_E.index.month==12]
df_indice_E1

df_indice_E1_1= df_indice_E1.copy()

df_indice_E1_1.index.year

df_indice_E1_1["FECHA"] = df_indice_E1_1.index.year
df_indice_E1_1.head()

df_E_1= df_indice_E1_1.set_index("FECHA")
df_E_1

"""# GUARDAR ARCHIVO EN CSV"""

df_E_1.to_csv("indice_E_(DIC).csv")

from google.colab import files
files.download("indice_E_(DIC).csv")