# -*- coding: utf-8 -*-
"""Indice C y E (1950-2006)_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tjBGsq7xS6dtAVlBn4CiCGvOeLANvsmN
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

indice = pd.read_csv("/content/drive/MyDrive/TPM_II/datos/indice_c_y_e/ecindex_ersstv5_CSV.csv")

indice.index = indice['year']
indice

indice1 = indice.drop(columns=['year'])
indice1

indice2 = indice1.loc["1950":"2006"] 
indice2

"""# GUARDAR ARCHIVO EN CSV"""

indice2.to_csv("df_indice_CyE(1950-2006).csv")

from google.colab import files
files.download("df_indice_CyE(1950-2006).csv")