# -*- coding: utf-8 -*-
"""fun corr E.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1noZYkHQ87h6lrUcOVAvxm0pIg9EKLkNw
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# PRECIPITACIÓN"""

Pisco_anom_mensual = xr.open_dataset("/content/drive/MyDrive/PROYECTO FINAL/PP anom mensual/Pisco_anom_mensual.nc")
Pisco_anom_mensual

"""# INDICE E"""

indiceE = pd.read_csv("/content/drive/MyDrive/PROYECTO FINAL/INDICE C y E (1981-2010)/df_indice_E_(1981-2010).csv")
indiceE

df_E_1= indiceE.set_index("Fecha")
df_E_1

#Correlacion
def cor_point_grid(y,x):
  res = np.corrcoef(y,x)[0,1]
  return res

cor_point_grid_example2 = xr.apply_ufunc(cor_point_grid,
                                        Pisco_anom_mensual,
                                        np.array(df_E_1).ravel(),
                                        input_core_dims=[["time"], ["Fecha"]],
                                        vectorize=True)


cor_point_grid_example2

cor_point_grid_example2.Prec.plot() 
plt.title("Corr PP - INDICE E (1981-2010)") 
plt.xlabel("Longitud")
plt.ylabel("Latitud")