# -*- coding: utf-8 -*-
"""ess Lima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YfPXxXbSn7dj3Ulg4DPp2VxrvJ79W92A
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install geopandas
# !pip install rioxarray

import rioxarray
from geopandas import read_file as gpd_read_file

Pisco_anom_masked_Lima = xr.open_dataset("/content/drive/MyDrive/PROYECTO FINAL/shp Lima/Pisco_anom_masked_Lima.nc")
Pisco_anom_masked_Lima

Pisco_anom_masked_Lima.Prec.isel(time=30).plot()

Pisco_anom_masked_Lima.mean(dim=["latitude", "longitude"]).Prec.plot()

Pisco_anom_masked_Lima.rolling(time=12, center=True).mean().mean(dim=("latitude","longitude")).Prec.plot()

plt.figure(figsize=(10,6))
plt.subplot(121)
Pisco_anom_masked_Lima.Prec.isel(time=30).plot()
plt.title("Anom_pp - LIMA (JULIO-1983)") 
plt.xlabel("Longitud")
plt.ylabel("Latitud")

plt.subplot(322)
Pisco_anom_masked_Lima.mean(dim=["latitude", "longitude"]).Prec.plot()
plt.title("CORTE TEMPORAL - LIMA")   
plt.xlabel("Años")
plt.ylabel(".")

plt.subplot(326)
Pisco_anom_masked_Lima.rolling(time=12, center=True).mean().mean(dim=("latitude","longitude")).Prec.plot()
plt.xlabel("Años") 
plt.ylabel(".")


plt.show()