# -*- coding: utf-8 -*-
"""ess_corr_rez.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bf6GdZhAfV0m9lE9Enca7hXyq6ndJKnA
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

indice2 = pd.read_csv("/content/drive/MyDrive/PROYECTO FINAL/INDICE C y E (1950-2006)_1/df_indice_CyE(1950-2006)_1.csv")
indice2

output_by_all = []
for m in [10, 11, 12, 1, 2, 3]: 
  
  output_by_m = []
  for lag_m in [-3, -2, -1, 0, 1, 2, 3]:
    
    if (lag_m + m) > 12:
      lag_m_real = np.abs(12 - (m + lag_m))
    elif (lag_m + m) <= 0:
      lag_m_real = np.abs(12 + (m + lag_m))
    else:
      lag_m_real = lag_m + m

    indice_c = indice2[indice2["month"] == m].C_index 
    indice_c = indice_c.reset_index(drop=True)
    indice_e = indice2[indice2["month"] == lag_m_real].E_index 
    indice_e = indice_e.reset_index(drop=True)

    output_by_m.append(pd.Series(pd.concat([indice_c, indice_e], axis=1).corr().iloc[0,1]))
  
  output_by_all.append(output_by_m)

output_by_all2 = [item for sublist in output_by_all for item in sublist]
output_by_all2

res = pd.DataFrame((np.array(output_by_all2)).reshape(6, 7))
res.columns = [-3, -2, -1, 0, 1, 2, 3]
res.index = [10, 11, 12, 1, 2, 3]
res