# -*- coding: utf-8 -*-
"""ess corr C and E  (1950-2006).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eNXJVxq7oEeomYG6IFvPXUfy-uXkeLIM
"""

from google.colab import drive
drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install netcdf4

import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# INDICE C"""

indice_C_NOV = pd.read_csv("/content/drive/MyDrive/PROYECTO FINAL/INDICE C (NOV)/indice_C_(NOV).csv")
indice_C_NOV

indice_C_NOV= indice_C_NOV.set_index("FECHA")
indice_C_NOV

"""# INDICE E"""

indice_E_DIC = pd.read_csv("/content/drive/MyDrive/PROYECTO FINAL/INDICE E (DIC)/indice_E_(DIC).csv")
indice_E_DIC

indice_E_DIC= indice_E_DIC.set_index("FECHA")
indice_E_DIC

"""# CORRELACIÓN"""

df_indices = pd.concat([indice_C_NOV,
                   indice_E_DIC], axis = 1)
df_indices.columns = ["indice_C_NOV", "indice_E_DIC"]

df_indices.corr()

df_indices.plot.scatter(x = "indice_E_DIC", y = "indice_C_NOV")
plt.title("Corr = 0.433804")   
plt.xlabel("SSTA NIÑO 1+2 (DICIEMBRE)") 
plt.ylabel("SSTA NIÑO 3,4 (NOVIEMBRE)")